//! Rendering. Pure — it takes the manifest values and the overlay TEXT, so the
//! shape of the output is testable without touching a filesystem.

use gates_config::Config;

/// The banner every rendered file carries. Present so a human editing the file
/// directly learns, in the file itself, that their edit will be overwritten.
pub const BANNER: &str =
    "<!-- Generated by render-agent-docs. Edit the manifest or the overlay, not this file. -->";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Target {
    pub name: String,
    pub path: String,
    pub title: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Manifest {
    /// Rule fragment names, in the order they should load.
    pub rules: Vec<String>,
    /// Directory the rendered `@` imports point at.
    pub rules_dir: String,
    /// Path to the repo-specific body, appended after the rules block.
    pub overlay: Option<String>,
    pub targets: Vec<Target>,
}

impl Manifest {
    pub fn from_config(cfg: &Config) -> Manifest {
        let targets = cfg
            .tables_under("targets")
            .into_iter()
            .filter_map(|name| {
                let path = cfg.string(&format!("targets.{name}.path"))?.to_string();
                let title = cfg
                    .string(&format!("targets.{name}.title"))
                    .unwrap_or(&path)
                    .to_string();
                Some(Target { name, path, title })
            })
            .collect();
        Manifest {
            rules: cfg.list("rules").unwrap_or_default(),
            rules_dir: cfg
                .string("rules_dir")
                .unwrap_or("~/.claude/rules")
                .trim_end_matches('/')
                .to_string(),
            overlay: cfg.string("overlay").map(str::to_string),
            targets,
        }
    }
}

/// The full text of one target file.
///
/// Whole-file generation is deliberate. A "managed region" between markers
/// leaves the rest hand-written, and the hand-written rest is exactly where the
/// two files drift apart. Anything a repo needs to say for itself goes in the
/// overlay, which both targets share.
pub fn render(manifest: &Manifest, target: &Target, overlay: Option<&str>) -> String {
    let mut out = String::new();
    out.push_str(&format!("# {}\n\n", target.title));
    out.push_str(BANNER);
    out.push_str("\n\n");

    if !manifest.rules.is_empty() {
        out.push_str("## Rules\n\n");
        out.push_str("Loaded by reference. Change a rule in one place and every repo that\n");
        out.push_str("imports it follows — see the rules index for what each one covers.\n\n");
        for rule in &manifest.rules {
            out.push_str(&format!("@{}/{}.md\n", manifest.rules_dir, rule));
        }
        out.push('\n');
    }

    if let Some(body) = overlay {
        let body = body.trim_start_matches('\u{feff}').trim();
        if !body.is_empty() {
            out.push_str(body);
            out.push('\n');
        }
    }
    out
}

#[cfg(test)]
#[path = "render_tests.rs"]
mod render_tests;
